apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-distribution
  namespace: argocd
spec:
  description: App Distribution Portal Project
  
  # Source repositories
  sourceRepos:
    - https://github.com/your-org/test-app-portal.git
  
  # Destination clusters and namespaces
  destinations:
    - namespace: app-distribution
      server: https://kubernetes.default.svc
  
  # Allowed cluster resources
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  
  # Allowed namespace resources
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: apps
      kind: '*'
    - group: networking.k8s.io
      kind: '*'
    - group: autoscaling
      kind: '*'
